### ISSUE TITLE
Package downloads could be cached 

### ISSUE THREAD

**Issue by lmoureaux** [lpetre-ulb/gemsuperbuild#1]
Since the packages that are downloaded are large, the superbuild would be much faster if the download and archive extraction could be skipped even if the call to `ExternalProject_Add` is slightly modified. This is especially relevant for `xDAQ` because of its many dependencies.

**Comment by lpetre-ulb** [comment]
There is already a cache with the CMake `ExternalProject`. However, it is not very efficient without `URL_HASH` (that I'll add) and if you delete the `build/` directory, it is gone. For a user of the supebuild it might not be very important, but as a developer I understand your concern.

What do you think of adding a cache in `${CMAKE_SOURCE_DIR}/cache` which could be pre-populated with small and/or hard-to-find archives (those currently in `thirdparty/`) ? This would be a quick and efficient fix.

**Comment by lmoureaux** [comment]
Tough call. I don't like the idea of putting the cache directory in `${CMAKE_SOURCE_DIR}`, but being able to nuke `${CMAKE_BINARY_DIR}` every now and then is very convenient.

Maybe the solution is to add an optional cached variable `${SUPERBUILD_CACHE_DIR}` where tarballs would be downloaded? This would give some flexibility to developers while regular users wouldn't see a difference. The cache could even be shared between different builds. Needless to say that such a feature would need to be documented ;-)

**Comment by lpetre-ulb** [comment]
Sure, there are advantages and drawbacks. The big advantage in favor of the cache directory in `${CMAKE_SOURCE_DIR}` : it can easily be pre-populated. Also, it consists of sources, so it belongs there in some sense.

I like your idea of `${SUPERBUILD_CACHE_DIR}`. It could also be populated by copying files from `${CMAKE_SOURCE_DIR}`. Let's choose for this solution then.

What would be the sanest default for `${SUPERBUILD_CACHE_DIR}` ? `${CMAKE_BINARY_DIR}/cache` ?
