### ISSUE TITLE
Discussion about CI and CD

### ISSUE THREAD

**Issue by lpetre-ulb** [lpetre-ulb/gemsuperbuild#12]
With the PR #11, we will reach successful builds on CC7, Debian and Archlinux. We don't want to loose the compatibility with new commits, but we also want to avoid manually testing every release on every distribution manually. This is why we need CI. CI would also help us testing the compatibility between versions so that the superbuild is always in a working state. 

There a multiple alternatives for CI :

* `GitLab CI` : The CERN provides an instance where we can run tests. However, it is not possible to run GitHub integrated CI/CD for imported project, ~~an Enterprise license~~ _a recent Premium version_ is required. The solution would be to move to GitLab and keep a public mirror on GitHub although the solution is not used for the other GEM projects. Using `GitLab CI` would also let us run private workers where tests involving hardware could be run.
* `Drone.io` : It integrates well with GitHub and is mainly self-hosted. We'd only new one build server, ideally connected to GEM hardware for future tests. Can be a good solution if we do not reach 10.000 per year.
* `Travis-CI` : While it is technically possible to run a self-hosted instance, it requires a lot of work and maintenance. This solution, which is integrable into GitHub, would then not allow tests involving hardware.

Regarding the CD, this is not high priority. In the short term, the superbuild will not be used to create packages, but will used to provide a development environment. Packaging the GEM software could definitively be done by calling each project packaging target, but that would require a environment where dependencies are installed.

**Comment by lpetre-ulb** [comment]
As discussed in private, the `GitLab-CI` seems the most advantageous solution. We can rely on the CERN infrastructure with a very complete tool.

Did we converge on this ? @lmoureaux ?

**Comment by lmoureaux** [comment]
Gitlab CI FTW.

**Comment by lpetre-ulb** [comment]
Issue solved, the repository has been moved to the CERN GitLab in order to get the CI (which is enabled).
