### ISSUE TITLE
Default installation path

### ISSUE THREAD

**Issue by lpetre-ulb** [lpetre-ulb/gemsuperbuild#7]
Currently all the packages are installed in `build/install`. This is not a ideal location when one needs to use the binaries.

The idea is to let the user chose where the packages must be installed (via de standard `CMAKE_INSTALL_PREFIX` variable). However, a safe and easy-to-use default should be provided.

As a first idea, `${CMAKE_SOURCE_DIR}/install` seems appropriate. What do you think of this location ? Have you better ideas ?

**Comment by lmoureaux** [comment]
If `${CMAKE_SOURCE_DIR}/install` is in `.gitignore`, I think it's ok to install there.

Do you have a plan to support packaging of the resulting binaries? If yes would you use per-component prefixes in `/opt`? I'm asking because I think that the layout of the `install` directory should be as close as possible.

**Comment by lpetre-ulb** [comment]
Sure it will be in `.gitignore`. ;-)

After second thoughts, I think the variable should be named something similar to `${GEM_SUPERBUILD_INSTALL_DIR}`. I don't plan support packaging the resulting binaries directly : for third-party packages, I would rely on their build systems (forget about `xDAQ` on Debian systems). For GEM packages, I plan to trigger their own packaging targets.

For a superbuild, the install directories would be `${GEM_SUPERBUILD_INSTALL_DIR}/${GEM_TARGET}/${CMAKE_INSTALL_PREFIX}` with the proper `RPATH`). For the packages, their installation path will be `${CMAKE_INSTALL_PREFIX}`. I'm still thinking for the `RPATH` in this case.

**Comment by lpetre-ulb** [comment]
Fixed with https://github.com/lpetre-ulb/gemsuperbuild/commit/6f65436d1ae51138c0eb46ded31961883813f619.
